### PR TITLE
[Misc] Fix staticcheck findings under pkg/

### LINKED ISSUE #556: Fix staticcheck findings in pkg/controller
## Summary

`staticcheck` reports several issues in `pkg/controller/...` that should be cleaned up.

### U1000 — Unused code (7 instances)

- `pkg/controller/v1beta1/acceleratorclass/controller.go:152` — `matchNodeSelectorTerm`
- `pkg/controller/v1beta1/acceleratorclass/controller.go:170` — `matchNodeSelectorExpressions`
- `pkg/controller/v1beta1/acceleratorclass/controller.go:212` — `matchNodeSelectorFields`
- `pkg/controller/v1beta1/acceleratorclass/controller.go:225` — `extractNodeFields`
- `pkg/controller/v1beta1/inferenceservice/cleanup.go:140` — `cleanupRemovedComponentsDynamic`
- `pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go:83` — `getDeploymentName`
- `pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go:104` — `getDeploymentName`

### ST1019 — Duplicate import (1 instance)

- `pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/strategies/gateway_api_strategy.go:15-16` — `knative.dev/pkg/apis` imported twice

### SA5011 — Possible nil pointer dereference (1 instance)

- `pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler_test.go:296` — pointer dereferenced after a nil check on line 293 suggests it can be nil

### SA4022 — Address of variable cannot be nil (5 instances)

- `pkg/controller/v1beta1/inferenceservice/utils/merging.go` lines 186, 202, 210, 234, 261 — redundant nil checks on variable addresses

## Proposed fix

- Remove unused functions
- Deduplicate the import
- Guard or restructure the nil dereference in the test
- Remove redundant nil-address checks

### PR DESCRIPTION
**Pull request by heymrbox**
## What this PR does

Fix static analysis issues in pkg/

## Why we need it

staticcheck reports multiple issues under pkg/. 

Fixes #556 

## How to test

make test

## Checklist

- [x] Tests added/updated (if applicable)
- [ ] Docs updated (if applicable)
- [x] `make test` passes locally

### CODE REVIEW

File: pkg/storage/providers/s3/utils.go [hunk 1]
```diff
@@ -19,113 +15,3 @@ func parseS3URI(uri string) (bucket string, key string, err error) {
 
 	return components.Bucket, components.Prefix, nil
 }
-
-// buildS3URI constructs an S3 URI from bucket and key
-func buildS3URI(bucket, key string) string {
```
Comment (pallasathena92) [inline pkg/storage/providers/s3/utils.go:24]: we delete this because we didn't use it? 
we don't have download from s3 and gcp for now, but we will keep this helper function for others use s3 and gcp.

Comment (heymrbox) [reply pkg/storage/providers/s3/utils.go:24]: good call, restored them

File: pkg/runtimeselector/matcher.go [hunk 2]
```diff
@@ -214,7 +214,8 @@ func (m *DefaultRuntimeMatcher) evaluateFormatMatch(model *v1beta1.BaseModelSpec
 	}
 
 	// Check model format
-	if format.ModelFormat != nil && &model.ModelFormat != nil {
```
Comment (pallasathena92) [inline pkg/runtimeselector/matcher.go:217]: just remove &model.ModelFormat != nil

File: go.sum [hunk 3]
```diff
@@ -15,61 +15,221 @@ cloud.google.com/go v0.56.0/go.mod h1:jr7tqZxxKOVYizybht9+26Z/gUq7tiRzu+ACVAMbKV
...
+cloud.google.com/go/appengine v1.9.3/go.mod h1:DtLsE/z3JufM/pCEIyVYebJ0h9UNPpN64GZQrYgOSyM=
+cloud.google.com/go/area120 v0.9.3/go.mod h1:F3vxS/+hqzrjJo55Xvda3Jznjjbd+4Foo43SN5eMd8M=
+cloud.google.com/go/artifactregistry v1.16.1/go.mod h1:sPvFPZhfMavpiongKwfg93EOwJ18Tnj9DIwTU9xWUgs=
+cloud.google.com/go/asset v1.20.4/go.mod h1:DP09pZ+SoFWUZyPZx26xVroHk+6+9umnQv+01yfJxbM=
+cloud.google.com/go/assuredworkloads v1.12.3/go.mod h1:iGBkyMGdtlsxhCi4Ys5SeuvIrPTeI6HeuEJt7qJgJT8=
 cloud.google.com/go/auth v0.16.1 h1:XrXauHMd30LhQYVRHLGvJiYeczweKQXZxsTbV9TiguU=
 cloud.google.com/go/auth v0.16.1/go.mod h1:1howDHJ5IETh/LwYs3ZxvlkXF48aSqqJUM+5o02dNOI=
 cloud.google.com/go/auth/oauth2adapt v0.2.8 h1:keo8NaayQZ6wimpNSmW5OPc283g65QNIiLpZnkHRbnc=
 cloud.google.com/go/auth/oauth2adapt v0.2.8/go.mod h1:XQ9y31RkqZCcwJWNSx2Xvric3RrU88hAYYbjDWYDL+c=
+cloud.google.com/go/automl v1.14.4/go.mod h1:sVfsJ+g46y7QiQXpVs9nZ/h8ntdujHm5xhjHW32b3n4=
```
Comment (pallasathena92) [inline go.sum]: would you try to tidy go sum here
